name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.28.1

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=20

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test Run
        run: |
          cd ${{github.workspace}}/build
          ./todo_v1 <<< "q"